// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniB2B.DataAccess;

#nullable disable

namespace MiniB2B.DataAccess.Migrations
{
    [DbContext(typeof(MiniB2BContext))]
    [Migration("20260919134927_AddSliderEntity")]
    partial class AddSliderEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniB2B.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("MiniB2B.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MiniB2B.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Elektronik Ürünler",
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ofis Kırtasiye",
                            Name = "Kırtasiye"
                        });
                });

            modelBuilder.Entity("MiniB2B.Entities.GridColumnConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HeaderText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Width")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GridColumnConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HeaderText = "Görsel",
                            IsVisible = true,
                            OrderIndex = 1,
                            PropertyName = "ImageUrl",
                            RenderType = "Image",
                            TableName = "Product",
                            Width = "60px"
                        },
                        new
                        {
                            Id = 2,
                            HeaderText = "Ürün Kodu",
                            IsVisible = true,
                            OrderIndex = 2,
                            PropertyName = "ProductCode",
                            RenderType = "Text",
                            TableName = "Product"
                        },
                        new
                        {
                            Id = 3,
                            HeaderText = "Ürün Adı",
                            IsVisible = true,
                            OrderIndex = 3,
                            PropertyName = "ProductName",
                            RenderType = "Text",
                            TableName = "Product"
                        },
                        new
                        {
                            Id = 4,
                            HeaderText = "Marka",
                            IsVisible = true,
                            OrderIndex = 4,
                            PropertyName = "Brand",
                            RenderType = "Text",
                            TableName = "Product"
                        },
                        new
                        {
                            Id = 5,
                            HeaderText = "Fiyat",
                            IsVisible = true,
                            OrderIndex = 5,
                            PropertyName = "Price",
                            RenderType = "Price",
                            TableName = "Product"
                        },
                        new
                        {
                            Id = 6,
                            HeaderText = "Stok",
                            IsVisible = true,
                            OrderIndex = 6,
                            PropertyName = "StockQuantity",
                            RenderType = "StockStatus",
                            TableName = "Product",
                            Width = "100px"
                        },
                        new
                        {
                            Id = 7,
                            HeaderText = "İşlem",
                            IsVisible = true,
                            OrderIndex = 7,
                            PropertyName = "Id",
                            RenderType = "Action",
                            TableName = "Product",
                            Width = "150px"
                        });
                });

            modelBuilder.Entity("MiniB2B.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MiniB2B.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MiniB2B.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CriticalStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialCode1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialCode2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Dell",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 9, 19, 16, 49, 26, 789, DateTimeKind.Local).AddTicks(516),
                            CriticalStockLevel = 5,
                            Description = "Yüksek performanslı iş bilgisayarı.",
                            ImageUrl = "/images/dell_laptop_product_1789753837200.jpg",
                            ManufacturerCode = "DELL-XPS-2026",
                            Price = 45000m,
                            ProductCode = "LP-XPS15",
                            ProductName = "Dell XPS 15 Laptop",
                            SpecialCode1 = "YENI-NESIL",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Logitech",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 9, 19, 16, 49, 26, 789, DateTimeKind.Local).AddTicks(532),
                            CriticalStockLevel = 10,
                            Description = "Ergonomik kablosuz mouse.",
                            ImageUrl = "/images/logitech_mouse_product_1789753847396.jpg",
                            ManufacturerCode = "LOGI-MX3",
                            Price = 2500m,
                            ProductCode = "MS-MX3",
                            ProductName = "Logitech MX Master 3",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Copier",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 9, 19, 16, 49, 26, 789, DateTimeKind.Local).AddTicks(533),
                            CriticalStockLevel = 100,
                            Description = "Premium kalite fotokopi kağıdı.",
                            ImageUrl = "/images/a4_paper_product_1789753857408.jpg",
                            Price = 120m,
                            ProductCode = "KP-A4",
                            ProductName = "A4 Fotokopi Kağıdı (500'lü)",
                            SpecialCode1 = "TOPTAN",
                            StockQuantity = 500
                        });
                });

            modelBuilder.Entity("MiniB2B.Entities.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/b2b_banner_welcome_1789753868740.jpg",
                            IsActive = true,
                            OrderIndex = 1,
                            Title = "Banner 1"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/b2b_banner_stock_1789753880181.jpg",
                            IsActive = true,
                            OrderIndex = 2,
                            Title = "Banner 2"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/b2b_banner_discount_1789753891697.jpg",
                            IsActive = true,
                            OrderIndex = 3,
                            Title = "Banner 3"
                        });
                });

            modelBuilder.Entity("MiniB2B.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 19, 16, 49, 26, 789, DateTimeKind.Local).AddTicks(555),
                            Email = "admin@minib2b.com",
                            FirstName = "Admin",
                            LastName = "User",
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 19, 16, 49, 26, 789, DateTimeKind.Local).AddTicks(557),
                            Email = "customer@minib2b.com",
                            FirstName = "Test",
                            LastName = "Customer",
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Role = "Customer",
                            Username = "customer"
                        });
                });

            modelBuilder.Entity("MiniB2B.Entities.Cart", b =>
                {
                    b.HasOne("MiniB2B.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniB2B.Entities.CartItem", b =>
                {
                    b.HasOne("MiniB2B.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniB2B.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniB2B.Entities.Order", b =>
                {
                    b.HasOne("MiniB2B.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniB2B.Entities.OrderItem", b =>
                {
                    b.HasOne("MiniB2B.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniB2B.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniB2B.Entities.Product", b =>
                {
                    b.HasOne("MiniB2B.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniB2B.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("MiniB2B.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniB2B.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
